### ISSUE TITLE
Missing interaction between Ascetic Style and Crusarder's Flurry

### ISSUE THREAD

**Issue by Mythalar** [Truinto/KingmakerFumi#3]
Hey there =)

I was doing some build testing and i think the Ascetic Style feat does not take into account the Crusader's Flurry feat (CotW), that can make favored weapons as monk weapons.

At least some abilities such as Stunning fist do not work with glaives (Shelyn favored weapon), but it works perfectly with a staff.

On the same topic a little question : what should be used with Ascetic Style? The monk ki strike against DR ? Some other Style feats (with dual style)?

Thank you so much y the way, some great additions 'o'

**Comment by Truinto** [comment]
You change a weapon from polearm to monk type, then to unarmed type. Well, that takes it to the extreme :D

I looked my code up and unfortunately it would be quite difficult to weave in another check (for Crusader's Flurry). That is because I extent Holic's weapon mapping and it only allows for a single check (which I already used up for Ascetic Style).

Sorry, I won't include it.

**Comment by Mythalar** [comment]
Well, I tried ! ^^

Thanks, I should be happy to flurry with it already =)
